package com.example.erman.photomapnavigation;

/**
 * Created by erman on 31.12.2014.
 */
public enum RequestTask {
    SIGN_IN_TASK, GET_OWN_EVENTS_TASK, GET_ACCESSABLE_EVENTS_TASK, DOWNLOAD_OWN_EVENTS_ROOT_PHOTOS, DOWNLOAD_ACCESSABLE_EVENTS_ROOT_PHOTOS,
    GET_EVENTS_PHOTOS, DOWNLOAD_EVENTS_PHOTOS, GET_PHOTO_TASK, NEW_EVENT_TASK, DOWNLOAD_NEW_EVENT_ROOT_PHOTO;
}
